### ISSUE TITLE
Multiple envkeys on the same server

### ISSUE THREAD

**Issue by Hugoberry** [envkey/envkey-python#10]
What would be the correct way of running multiple envkeys on the same server and avoiding environment variable clashes?
For example, APP1 uses ENVKEY_APP1 and APP2 uses ENVKEY_APP2. I don't have any problems running the apps in isolation, however, once there are ENVKEY variable clashes between these two apps there is the problem of precedence when importing envkey.
The same variable, say `DATABASE_NAME` gets rewritten if the APP1 is still running and APP2 imports ENVKEY_APP2 with a different value for `DATABASE_NAME`.

**Comment by danenania** [comment]
Hey @Hugoberry, are you using EnvKey v1? In EnvKey v2, you can place each `ENVKEY` in a file at `~/.envkey/apps/[appId]/.env` (the path will be displayed with the `appId` included when you generate the server `ENVKEY`).

In v1, you would need to set each `ENVKEY` environment variable with a different name: like `ENVKEY_APP1` and `ENVKEY_APP2` as you said, and then pass it as the `ENVKEY` variable when you start each server process:

```
$ ENVKEY=$ENVKEY_APP1 python app1.py
$ ENVKEY=$ENVKEY_APP2 python app2.py
```

Does that help?

**Comment by danenania** [comment]
Closing this, but happy to re-open if it's still an issue for you @Hugoberry
