### ISSUE TITLE
ValueError: ENVKEY invalid. Couldn't load vars.

### ISSUE THREAD

**Issue by ghost** [envkey/envkey-python#2]
Hello,
I am using python 3.6 and I have my file in the root folder of my Django project. I have the ENVKEY="" inside the `.env` and this file's name is inside `.gitignore`. I do try running my server or doing ipython, everytime i do import envkey the following error trace pops up.

````
/opt/bitnami/python/lib/python3.6/site-packages/envkey/loader.py in load(is_init, cache_enabled, dot_env_enabled, dot_env_path)
     23     raise ValueError("ENVKEY missing - must be set as an environment variable or in a gitignored .env file in the root of your project. Go to https://www.envkey.com if you don't know what an ENVKEY is.")
     24 
---> 25   fetch_res = fetch_env(key, cache_enabled=cache_enabled)
     26 
     27   vars_set = dict()

/opt/bitnami/python/lib/python3.6/site-packages/envkey/fetch.py in fetch_env(key, cache_enabled)
     45 
     46   if res.startswith("error: "):
---> 47     raise ValueError("ENVKEY invalid. Couldn't load vars.")
     48 
     49   return json.loads(res)

ValueError: ENVKEY invalid. Couldn't load vars.
```
I have Django 2.1, python3.6, Ubuntu 16.04. My project is hold by an Apache2 server .

**Comment by ghost** [comment]
I fixed it for local development. However, in my deployment server it does not work. I use apache.

**Comment by danenania** [comment]
Hi @ejuarez1293  - on your server, can you verify that:

1 - `os.environ["ENVKEY"]` is set to a valid ENVKEY. 

2 - You can ping `https://env.envkey.com/health` from your server (sometimes network config can block outgoing requests).

**Comment by ghost** [comment]
@danenania,
Currently, this is what is display from both my local and server environments
```
ping https://env.envkey.com/health
   ping: https://env.envkey.com/health: Name or service not known
```
I can access it though my browser though

**Comment by danenania** [comment]
Hmm actually can you try with curl: `curl https://env.envkey.com/health`

Any difference?

**Comment by ghost** [comment]
Yeah, I get the raw content.
if I do `eval $(envkey-source env.file)` works. if I export the envkey into a environmetn variable like `export ENVKEY=...` kind of works. For local development import envkey works. In my server, my django app does import envkey, and for development process it works, but as soon my apache2 server runs it, the envkey doesn't go through. I did utterly ugly methods, which was doing a os.envion['MY_SECRET_VALUE'] =  value, but I dislike this.

**Comment by danenania** [comment]
Gotcha - yeah it sounds like getting the `ENVKEY` environment variable through to the Apache process is the issue. I don't have a lot of Apache experience, but this looks like it could help: https://httpd.apache.org/docs/2.4/env.html

**Comment by danenania** [comment]
Closing this since it doesn't seem to be an issue with the package, but happy to continue the convo if you're still stuck.

I'd also be happy to add a note to the readme (or accept a PR) on any specific steps needed to play nicely with Apache.

**Comment by ghost** [comment]
Thank you though! You actually responded very fast! I have found a way around it, but it is not using envekey anymore. I need to figure out a way to user envkey, apache, and django together in deployment. If I ever figure it out, I will let you know so others can follow my solution!
