### ISSUE TITLE
envkey does not work in AWS Lambda

### ISSUE THREAD

**Issue by kylepolich** [envkey/envkey-python#4]
We are using [Chalice](https://github.com/aws/chalice) to package a Hello World + ENVKEY app and run it as a lambda function.  The deployment goes fine.  I confirmed that the Lambda function has a correct `ENVKEY` value:

![image](https://user-images.githubusercontent.com/1054674/61831120-c001ad80-ae21-11e9-9fbf-6fa4ad99bb75.png)

I also confirmed that Chalice successfully bundles `envkey` into our zip file which is used to create the lambda function.  However, when I invoke the function, I get this exception:

```
  File \"/var/lang/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)
  File \"/var/lang/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)
  File \"<frozen importlib._bootstrap>\", line 696, in _load
  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked
  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module
  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed
  File \"/var/task/app.py\", line 14, in <module>\n    import envkey
  File \"/var/task/envkey/__init__.py\", line 4, in <module>\n    load(is_init=True)
  File \"/var/task/envkey/loader.py\", line 25, in load\n    fetch_res = fetch_env(key, cache_enabled=cache_enabled)
  File \"/var/task/envkey/fetch.py\", line 46, in fetch_env\n    res = subprocess.check_output(args).decode().rstrip()
  File \"/var/lang/lib/python3.7/subprocess.py\", line 395, in check_output\n    **kwargs).stdout
  File \"/var/lang/lib/python3.7/subprocess.py\", line 472, in run\n    with Popen(*popenargs, **kwargs) as process:
  File \"/var/lang/lib/python3.7/subprocess.py\", line 775, in __init__\n    restore_signals, start_new_session)
  File \"/var/lang/lib/python3.7/subprocess.py\", line 1522, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)
```

It appears as though `envkey` wants to do some caching on the local filesystem?  This is not possible as Lambda does not allow it.

Yet, the nodejs `envkey` library deploys to AWS Lambda flawlessly on the first attempt.  Is it possible for the python implementation do function the same way?

**Comment by kylepolich** [comment]
It's worth noting that the error occurs on `import envkey`, so I am not able to try using `cache_enabled=False` as a work around for Lambda's lack of access to local disk

**Comment by danenania** [comment]
Hi!

Could you try setting  ENVKEY_DISABLE_AUTOLOAD=1 as an environment variable
in addition to the ENVKEY? Then you can run the load function manually:
envkey.load(cache_enabled=False, dot_env_enabled=False)

Does that help?

**Comment by kylepolich** [comment]
HI @danenania , yes that took care of our issue!  Thanks for the tip.

**Comment by danenania** [comment]
Good to hear @kylepolich!

**Comment by hellorashid** [comment]
Hello! I am also trying to run on Lambda, and ran into the same error. I have followed all the steps above: 
- Setting ENVKEY_DISABLE_AUTOLOAD=1 
- Using envkey.load(cache_enabled=False, dot_env_enabled=False)

However I am still getting same error. Would you have any suggestions? 
Thank you!

**Comment by danenania** [comment]
@hellorashid Hmm envkey-python wouldn't write anything to the filesystem with `ENVKEY_DISABLE_AUTOLOAD=1` and `cache_enabled=False`. Could you confirm that `ENVKEY_DISABLE_AUTOLOAD` variable is defined at the point you're calling `import envkey`?

**Comment by hellorashid** [comment]
Yep, I just confirmed - I printed out `ENVKEY_DISABLE_AUTOLOAD` at the top of the file, and it shows value of 1. 
For further context, here is my code: 

```
import os
print(os.environ.get("ENVKEY_DISABLE_AUTOLOAD"))

import boto3
from botocore.config import Config
import pandas as pd
from shapely.geometry import shape, Point
import numpy as np
import requests
import envkey

#Python Imports:
import json
import _pickle as cPickle
import datetime
from datetime import timezone
from dateutil.relativedelta import relativedelta
from requests.auth import HTTPBasicAuth

envkey.load(cache_enabled=False, dot_env_enabled=False)
```


And the error I am getting: 
```
[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/envkey/ext/envkey-fetch_1.2.4_linux_amd64/envkey-fetch'
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/app.py", line 25, in <module>
    envkey.load(cache_enabled=False, dot_env_enabled=False)
  File "/var/task/envkey/loader.py", line 26, in load
    fetch_res = fetch_env(key, cache_enabled=cache_enabled)
  File "/var/task/envkey/fetch.py", line 46, in fetch_env
    res = subprocess.check_output(args).decode(encoding="utf-8").rstrip()
  File "/var/lang/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/var/lang/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/var/lang/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/var/lang/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

```

**Comment by danenania** [comment]
@hellorashid Thanks for that info. This actually looks like a different problem than what the OP had. The problem isn't writing to the filesystem, but executing the `envkey-fetch` binary that is included with envkey-python. It seems that perhaps it's necessary to give `/var/task/envkey/ext/envkey-fetch_1.2.4_linux_amd64/envkey-fetch` execution permissions.

**Comment by hellorashid** [comment]
I've attempted to use the following to give execution permissions, but I'm still encountering the same error. 
`# subprocess.run(["chmod", "+xrw", "/var/task/envkey/ext/envkey-fetch_1.2.4_linux_amd64/envkey-fetch"])
`
In the meantime we are just not using Envkey on Lambda, but if anyone is able to do so successfully please let me know, any help is much appreciated. Thank you!

**Comment by danenania** [comment]
@hellorashid I'm a bit stumped as we have a number of customers using various EnvKey packages on Lambda without issue, and all make the same call to the `envkey-fetch` binary--so if it was a general problem with Lambda blocking calls to executables, I would expect others to be affected as well. Sorry I can't be of more help :-/

That said, it's on our roadmap to really dig in on Lambda and optimize the experience, as we know there are many ways we can improve it, so stay tuned.
