### ISSUE TITLE
Feature suggestion: add a get function to the main envkey module

### ISSUE THREAD

**Issue by drcongo** [envkey/envkey-python#5]
I find in my projects I'm using a pattern like this to access the vars from envkey...

```
import os
import envkey  # NOQA

FOO = os.environ.get('FOO')
```

Two things bother me about this, one is that I need to add `# NOQA` so that Flake8 doesn't get upset about an unused import, and the other is that there's an extra import of `os` or `os.environ`. It feels like it would make sense to be able to do this instead...

```
import envkey

FOO = envkey.get('FOO')
```

with envkey just passing on the call to `os.environ`'s get. 

Happy to do this as a PR if you like the idea.

**Comment by danenania** [comment]
Hey Andy! Sure, I’d be open to a PR for this as syntactic sugar. I’d still
consider os.environ to be the ‘default’ way to access vars to maintain the
consistency of envkey using just plain ol’ environment variables across all
the packages, but I see no harm in adding this as another option.

**Comment by drcongo** [comment]
Thanks Dan! PR is in. No rush on a release, and given that it is just sugar I agree with you that os.environ should remain the default (and documented) way to access the vars.

**Comment by danenania** [comment]
Great, will merge/release when I have a chance. Thanks!

**Comment by danenania** [comment]
@drcongo Sorry, had lost track of this, but finally merged it along with some other fixes, and added a couple examples to README. It's live in version `1.2.5` on pypi. Thanks again!

**Comment by drcongo** [comment]
No worries Dane, hope you’re keeping well.
